[project]
name = "ygo-fm-clone"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.11.*"
dependencies = [
    "cython>=3.2.4",
    "numpy>=2.4.1",
    "pygame>=2.6.1",
    "rich>=14.3.1",
    "ruff>=0.14.14",
    "setuptools>=80.10.2",
]
